### ISSUE TITLE
parse_fastq should be split into separate parsing, filtering, and writing functions

### ISSUE THREAD

**Issue by kylebittinger** [PennChopMicrobiomeProgram/decontam#4]
Filtering may not require a function, can probably just write directly in calling code

**Comment by kylebittinger** [comment]
Example in calling code:

```
reads = parse_fastq(infile)
for read in reads:
    if read.desc in not_human:
        write_fastq(outfile, read)
```

If you use a yield statement inside parse_fastq, this will read from the input file only as necessary.

**Comment by apatil1** [comment]
resolved
